# Generated by Django 4.2.7 on 2023-11-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('num_passenger_seats', models.IntegerField()),
                ('license_plate', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TripPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('distance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('starting_point', models.CharField(max_length=20)),
                ('ending_point', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TripRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='carpool_app.trip')),
            ],
        ),
    ]
