# Generated by Django 4.2.7 on 2023-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippart',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='trip_parts', to='carpool_app.tripregistration'),
        ),
    ]
