# Generated by Django 4.2.7 on 2023-11-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0002_alter_car_owner_alter_review_trip_alter_trip_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='trippart',
            old_name='trip_part_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tripregistration',
            old_name='trip_registration_id',
            new_name='id',
        ),
    ]
