# Generated by Django 4.2.7 on 2023-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0004_alter_review_reviewee_alter_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
