# Generated by Django 4.2.7 on 2023-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool_app', '0006_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='trippart',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
